const listOfBrands = [
    "Acura",
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "BMW",
    "Bentley Motors",
    "Bugatti",
    "Buick",
    "Ford",
    "Honda",
    "Mercedes-Benz",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volkswagen",
    "Audi",
    "BMW",
    "Mercedes-Benz",
    "Porsche",
    "Bentley",
    "Bugatti",
    "Toyota",
    "Honda",
    "Nissan",
    "Mazda",
    "Subaru",
    "Mitsubishi",
    "Lexus",
    "Acura",
    "Ford",
    "Chevrolet",
    "GMC",
    "Cadillac",
    "Chrysler",
    "Dodge",
    "Tesla",
    "Fiat",
    "Alfa Romeo",
    "Lamborghini",
    "Ferrari",
    "Maserati",
    "Hyundai",
    "Kia",
    "Genesis",
    "Jaguar",
    "Land Rover",
    "Aston Martin",
    "Mini",
    "Geely",
    "SAIC Motor",
    "BYD",
    "Renault",
    "Peugeot",
    "Citroën",
    "Rivian",
    "Lucid Motors",
    "Polestar",
    "Lotus",
    "Volvo"
]